final genshinCharacter = [
    {
      'Name': 'Barbara',
      'Element': 'Hydro',
      'Weapon': 'Catalyst',
      'Nation': 'Monstadt',
      'Rarity': 4,
      'Image': 'assets/Monsta'
    },
    {
      'Name': 'Diluc',
      'Element': 'Pyro',
      'Weapon': 'Claymore',
      'Nation': 'Monstadt',
      'Rarity': 5,
    },
    {
      'Name': 'Fischl',
      'Element': 'Electro',
      'Weapon': 'Bow',
      'Nation': 'Monstadt',
      'Rarity': 4,
    },
    {
      'Name': 'Jean',
      'Element': 'Anemo',
      'Weapon': 'Sword',
      'Nation': 'Monstadt',
      'Rarity': 5,
    },
    {
      'Name': 'Kaeya',
      'Element': 'Cryo',
      'Weapon': 'Sword',
      'Nation': 'Monstadt',
      'Rarity': 4,
    },
    {
      'Name': 'Lisa',
      'Element': 'Electro',
      'Weapon': 'Catalyst',
      'Nation': 'Monstadt',
      'Rarity': 4,
    },
    {
      'Name': 'Mona',
      'Element': 'Hydro',
      'Weapon': 'Catalyst',
      'Nation': 'Monstadt',
      'Rarity': 5,
    },
    {
      'Name': 'Razor',
      'Element': 'Electro',
      'Weapon': 'Claymore',
      'Nation': 'Monstadt',
      'Rarity': 4,
    },
    {
      'Name': 'Venti',
      'Element': 'Anemo',
      'Weapon': 'Bow',
      'Nation': 'Monstadt',
      'Rarity': 5,
    },
    {
      'Name': 'Albedo',
      'Element': 'Geo',
      'Weapon': 'Sword',
      'Nation': 'Monstadt',
      'Rarity': 5,
    },
    // Liyue
    {
      'Name': 'Xiangling',
      'Element': 'Pyro',
      'Weapon': 'Polearm',
      'Nation': 'Liyue',
      'Rarity': 4,
    },
    {
      'Name': 'Beidou',
      'Element': 'Electro',
      'Weapon': 'Claymore',
      'Nation': 'Liyue',
      'Rarity': 4,
    },
    {
      'Name': 'Chongyun',
      'Element': 'Cryo',
      'Weapon': 'Claymore',
      'Nation': 'Liyue',
      'Rarity': 4,
    },
    {
      'Name': 'Ningguang',
      'Element': 'Geo',
      'Weapon': 'Catalyst',
      'Nation': 'Liyue',
      'Rarity': 4,
    },
    {
      'Name': 'Qiqi',
      'Element': 'Cryo',
      'Weapon': 'Sword',
      'Nation': 'Liyue',
      'Rarity': 5,
    },
    {
      'Name': 'Xiao',
      'Element': 'Anemo',
      'Weapon': 'Polearm',
      'Nation': 'Liyue',
      'Rarity': 5,
    },
    {
      'Name': 'Xingqiu',
      'Element': 'Hydro',
      'Weapon': 'Sword',
      'Nation': 'Liyue',
      'Rarity': 4,
    },
    {
      'Name': 'Zhongli',
      'Element': 'Geo',
      'Weapon': 'Polearm',
      'Nation': 'Liyue',
      'Rarity': 5,
    },
    {
      'Name': 'Ganyu',
      'Element': 'Cryo',
      'Weapon': 'Bow',
      'Nation': 'Liyue',
      'Rarity': 5,
    },
    {
      'Name': 'Hu Tao',
      'Element': 'Pyro',
      'Weapon': 'Polearm',
      'Nation': 'Liyue',
      'Rarity': 5,
    },
    // Inazuma
    {
      'Name': 'Ayaka',
      'Element': 'Cryo',
      'Weapon': 'Sword',
      'Nation': 'Inazuma',
      'Rarity': 5,
    },
    {
      'Name': 'Yoimiya',
      'Element': 'Pyro',
      'Weapon': 'Bow',
      'Nation': 'Inazuma',
      'Rarity': 5,
    },
    {
      'Name': 'Sayu',
      'Element': 'Anemo',
      'Weapon': 'Claymore',
      'Nation': 'Inazuma',
      'Rarity': 4,
    },
    {
      'Name': 'Raiden Shogun',
      'Element': 'Electro',
      'Weapon': 'Polearm',
      'Nation': 'Inazuma',
      'Rarity': 5,
    },
    {
      'Name': 'Kujou Sara',
      'Element': 'Electro',
      'Weapon': 'Bow',
      'Nation': 'Inazuma',
      'Rarity': 4,
    },
    {
      'Name': 'Kokomi',
      'Element': 'Hydro',
      'Weapon': 'Catalyst',
      'Nation': 'Inazuma',
      'Rarity': 5,
    },
    {
      'Name': 'Thoma',
      'Element': 'Pyro',
      'Weapon': 'Polearm',
      'Nation': 'Inazuma',
      'Rarity': 4,
    },
    {
      'Name': 'Itto',
      'Element': 'Geo',
      'Weapon': 'Claymore',
      'Nation': 'Inazuma',
      'Rarity': 5,
    },
    {
      'Name': 'Yae Miko',
      'Element': 'Electro',
      'Weapon': 'Catalyst',
      'Nation': 'Inazuma',
      'Rarity': 5,
    },
    {
      'Name': 'Kazuha',
      'Element': 'Anemo',
      'Weapon': 'Sword',
      'Nation': 'Inazuma',
      'Rarity': 5,
    },
    // Sumeru
    {
      'Name': 'Tighnari',
      'Element': 'Dendro',
      'Weapon': 'Bow',
      'Nation': 'Sumeru',
      'Rarity': 5,
    },
    {
      'Name': 'Collei',
      'Element': 'Dendro',
      'Weapon': 'Bow',
      'Nation': 'Sumeru',
      'Rarity': 4,
    },
    {
      'Name': 'Cyno',
      'Element': 'Electro',
      'Weapon': 'Polearm',
      'Nation': 'Sumeru',
      'Rarity': 5,
    },
    {
      'Name': 'Nilou',
      'Element': 'Hydro',
      'Weapon': 'Sword',
      'Nation': 'Sumeru',
      'Rarity': 5,
    },
    {
      'Name': 'Alhaitham',
      'Element': 'Dendro',
      'Weapon': 'Sword',
      'Nation': 'Sumeru',
      'Rarity': 5,
    },
    {
      'Name': 'Dehya',
      'Element': 'Pyro',
      'Weapon': 'Claymore',
      'Nation': 'Sumeru',
      'Rarity': 5,
    },
    {
      'Name': 'Layla',
      'Element': 'Cryo',
      'Weapon': 'Sword',
      'Nation': 'Sumeru',
      'Rarity': 4,
    },
    {
      'Name': 'Nahida',
      'Element': 'Dendro',
      'Weapon': 'Catalyst',
      'Nation': 'Sumeru',
      'Rarity': 5,
    },
    {
      'Name': 'Faruzan',
      'Element': 'Anemo',
      'Weapon': 'Bow',
      'Nation': 'Sumeru',
      'Rarity': 4,
    },
    {
      'Name': 'Kaveh',
      'Element': 'Dendro',
      'Weapon': 'Claymore',
      'Nation': 'Sumeru',
      'Rarity': 4,
    },
    // Fontaine
    {
      'Name': 'Lynette',
      'Element': 'Anemo',
      'Weapon': 'Sword',
      'Nation': 'Fontaine',
      'Rarity': 4,
    },
    {
      'Name': 'Lyney',
      'Element': 'Pyro',
      'Weapon': 'Bow',
      'Nation': 'Fontaine',
      'Rarity': 5,
    },
    {
      'Name': 'Freminet',
      'Element': 'Cryo',
      'Weapon': 'Claymore',
      'Nation': 'Fontaine',
      'Rarity': 4,
    },
    {
      'Name': 'Neuvillette',
      'Element': 'Hydro',
      'Weapon': 'Catalyst',
      'Nation': 'Fontaine',
      'Rarity': 5,
    },
    {
      'Name': 'Charlotte',
      'Element': 'Cryo',
      'Weapon': 'Catalyst',
      'Nation': 'Fontaine',
      'Rarity': 4,
    },
    {
      'Name': 'Clorinde',
      'Element': 'Electro',
      'Weapon': 'Sword',
      'Nation': 'Fontaine',
      'Rarity': 5,
    },
    {
      'Name': 'Navia',
      'Element': 'Geo',
      'Weapon': 'Claymore',
      'Nation': 'Fontaine',
      'Rarity': 5,
    },
    {
      'Name': 'Sigewinne',
      'Element': 'Hydro',
      'Weapon': 'Bow',
      'Nation': 'Fontaine',
      'Rarity': 5,
    },
    {
      'Name': 'Wriothesley',
      'Element': 'Cryo',
      'Weapon': 'Catalyst',
      'Nation': 'Fontaine',
      'Rarity': 5,
    },
    {
      'Name': 'Furina',
      'Element': 'Hydro',
      'Weapon': 'Sword',
      'Nation': 'Fontaine',
      'Rarity': 5,
    },
  ];